---
title: ""
format: html
---

::: {#hero-heading}
# Research

My research interests are primarily focused on methodological aspects in the development and fair evaluation of clinical prediction models (including machine learning) and have published extensively in this area (see [research output](https://research.birmingham.ac.uk/en/persons/gary-collins/publications/) or [google scholar](https://scholar.google.com/citations?hl=en&user=cVKF81gAAAAJ)).

SOME MORE BLURB AROUND PREDICTION METHDOLOGY  (to finish)

My other research interests lie in improving the transparency, openness and quality of health research, where I lead the [EQUATOR Network](https://www.equator-network.org/) activities in the UK.

In 2010, I established an international initiative to develop the [TRIPOD](https://www.tripod-statement.org/) reporting recommendations published in [2015](https://www.bmj.com/content/350/bmj.g7594) for studies developing and validating clinical prediction models. I led an update to these recommendations in 2024 to cover models developed using artificial intelligence and machine learning methods ([TRIPOD+AI](https://www.bmj.com/content/385/bmj-2023-078378)) and large language models ([TRIPOD-LLM](https://www.nature.com/articles/s41591-024-03425-5)).

I have also been involved in other guidance for artificial intelligence and machine learning studies in healthcare, including

-   [STARD-AI](https://www.nature.com/articles/s41591-025-03953-8): for AI based diagnostic test accuracy studies

-   [DECIDE-AI](https://www.bmj.com/content/377/bmj-2022-070904): for early-stage live clinical evaluation of AI systems

-   [CONSORT-AI](https://www.nature.com/articles/s41591-020-1034-x) / [SPIRIT-AI](https://www.nature.com/articles/s41591-020-1037-7): for AI intervention studies

-   [CHART](https://www.bmj.com/content/390/bmj-2024-083305): for evaluating chatbots providing medical advice

I am also involved in development of risk of bias tools for machine learning diagnostic test accuracy studies (QUADAS-AI) and prediction model studies ([PROBAST+AI](https://www.bmj.com/content/388/bmj-2024-082505)), and the [FUTURE-AI](https://www.bmj.com/content/388/bmj-2024-081554) principles for trustworthy and deployable artificial intelligence in healthcare.

::: {#hero-heading}
## Other reporting guidelines

I have also been involved in the development of numerous other reporting guidelines for other study designs, including the

-   [GATHER statement](https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(16)30388-9/fulltext) for studies providing global health estimates

-   [AGReMA statement](https://jamanetwork.com/journals/jama/fullarticle/2784353) for mediation analyses

-   2025 update of [SPIRIT](https://jamanetwork.com/journals/jama/fullarticle/2833408) and [CONSORT](https://www.bmj.com/content/389/bmj-2024-081123) guidelines for clinical trials

-   [SPIRIT-Surrogate](https://www.bmj.com/content/386/bmj-2023-078525) and [CONSORT-Surrogate](https://www.bmj.com/content/386/bmj-2023-078524) for trials with surrogate endpoints

I am also a steering group member, and former co-chair of the international [STRATOS Initiative](https://stratos-initiative.org/), which aims to provide accessible and accurate guidance in the design and analysis of observational studies, and I currently sit on the external advisory board for the Centre for Open Science [Transparency and Openness Promotion](https://www.cos.io/initiatives/top-guidelines) Guidelines.
:::
