---
title: ""
format: html
---

:::: {#hero-heading}
# TRIPOD Reporting guidelines

Transparent Reporting Items for a multivariable prediction model for individual Prognosis or Diagnosis

background and history (to do)

## **TRIPOD-2015**

The original 2015 TRIPOD statement was published simultaneoulsy in 11 journals (in alphabetical order), click the journal link below to take you to the paper

-   [Annals of Internal Medicine](https://doi.org/10.7326/M14-0697)

-   [BJOG](https://doi.org/10.1111/1471-0528.13244)

-   [British Journal of Cancer](https://doi.org/10.1038/bjc.2014.639)

-   [British Journal of Surgery](https://doi.org/10.1002/bjs.9736)

-   [BMJ](https://doi.org/10.1136/bmj.g7594)

-   [BMC Medicine](https://doi.org/10.1186/s12916-014-0241-z)

-   [Circulation](https://doi.org/10.1161/CIRCULATIONAHA.114.014508)

-   [Diabetic Medicine](https://doi.org/10.1111/dme.12654)

-   [European Journal of Clinical Investigation](https://doi.org/10.1111/eci.12376)

-   [European Urology](https://doi.org/10.1016/j.eururo.2014.11.025)

-   [Journal of Clinical Epidemiology](https://doi.org/10.1016/j.jclinepi.2014.11.010)

This was followed up with two further shorter papers

-   [Advances in Anatomic Pathology](https://doi.org/10.1097/PAP.0000000000000072)

-   [Clinical Chemistry](https://doi.org/10.1373/clinchem.2014.237883)

A detailed Explanataion and Elaboration paper with rationale and examples of good reporting accompanying the original 2015 statement is available

-   [TRIPOD Explanation & Elaboration](https://www.acpjournals.org/doi/10.7326/M14-0698)

TRIPOD-2015 has now been superseded with TRIPOD+AI (below)

## **TRIPOD-Cluster**

The growing availability of large datasets from sources such as electronic health records and individual participant data meta-analyses offers new opportunities and challenges for developing and validating prediction models. These data often include individuals from multiple clusters (for example, centres, regions, or studies).

Accounting for this clustering is crucial to avoid biased conclusions, assess heterogeneity in model performance, and improve the generalisability of prediction models across different settings. The original 2015 TRIPOD statement does not fully cover the specific methodological and analytical complexity in prediction model studies that are based on (and thus should account for) clustered data. We therefore developed TRIPOD-Cluster, a new reporting checklist for prediction model studies that are based on clustered datasets

-   [TRIPOD-Cluster](https://www.bmj.com/content/380/bmj-2022-071018): the checklist paper

-   [TRIPOD-Cluster Explanation & Elaboration](https://www.bmj.com/content/380/bmj-2022-071058): the explaantaory paper accompanying the checklist

## **TRIPOD-SRMA**

Many clinical specialties have numerous studies developing or validating prediction models for diagnostic or prognostic use. Systematic reviews and meta-analyses are important to summarise evidence on model performance. Such reviews are increasingly common and should be reported transparently and accurately. We therefore developed TRIPOD-SRMA to provide reporting recommendations to support high-quality reporting of systematic reviews and meta-analyses of prediction model studies.

-   [TRIPOD-SRMA](https://www.bmj.com/content/381/bmj-2022-073538): the checklist paper

## **TRIPOD+AI**

In 2019, we announced in a [Lancet commentary](https://doi.org/10.1016/S0140-6736(19)30037-6) that we were going to embark on an update to the original 2015 version of the TRIPOD Statement to reflect the increasing interest in applying artificial intelligence to healthcare problems driven by advances in machine learning.

A protocol describing our methodology was published in [BMJ Open](https://doi.org/10.1136/bmjopen-2020-048008). In 2024, we published the TRIPOD+AI recommendations in the BMJ. The recommendations now supersede the original 2015 recommendations.

-   [TRIPOD+AI](https://www.bmj.com/content/385/bmj-2023-078378): the checklist paper

I also wrote an opinion piece in the BMJ to accompany the TRIPOD+AI statement which you can read [here](https://doi.org/10.1136/bmj.q832) to provice some background and context. There is also a linked editorial written by Jérémie Cohen and Patrick Bossuyt which is available to read [here](https://doi.org/10.1136/bmj.q824).

We are in the process of writing an Explanation and Elaboration paper that provides much detail (watch this space). In the meantime [supplementary table 1](https://www.bmj.com/content/385/bmj-2023-078378/related#datasupp) of the TRIPOD+AI paper provides a bullet point 'Explanation and Elaboration Light version of some additional consideratioans and guidance.

## **TRIPOD-LLM**

As large language models (LLMs) become increasingly prevalent, we have also developed recommendations addressing the unique challenges of LLMs in biomedical applications and published in Nature Medicine

-   [TRIPOD-LLM](https://doi.org/10.1038/s41591-024-03425-5): the checklist paper

An interactive 'fillable' checklist is available [here](https://tripod-llm.vercel.app/)


## **TRIPOD-P**

## **TRIPOD-Code**

::::
